
dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: preview
  name: activiti-api
  repository: file://../activiti-api
